eureka:
  instance: server1
  client:
    service-url:
      defaultZone: http://server1:9001/eureka

server:
  port: 10010

spring:
  application:
    name: zuul-service
  http:
    converters:
      preferred-json-mapper: jackson
  jackson:
    time-zone: Asia/Shanghai

# \u53C2\u8003 org.springframework.cloud.netflix.ribbon.RibbonClientConfiguration
# \u53C2\u8003 org.springframework.cloud.netflix.ribbon.okhttp.OkHttpRibbonConfiguration
ribbon:
  okhttp:
    enabled: true
  http:
    client:
      enabled: false
  # \u5355\u4F4D\u6BEB\u79D2
  ReadTimeout: 20_000
  # Ribbon\u8FDE\u63A5\u6C60\u5927\u5C0F
  MaxTotalConnections: 315
  # \u540C\u4E00\u53F0\u5B9E\u4F8B\u6700\u5927\u91CD\u8BD5\u6B21\u6570,\u4E0D\u5305\u62EC\u9996\u6B21\u8C03\u7528
  MaxAutoRetries: 0


zuul:
  routes:
    api-user:
      # \u53CD\u5411\u4EE3\u7406\u4E0D\u8D70okHttp
      path: /invoice/**
      serviceId: invoice-service

